### ISSUE TITLE
Refactoring Hardcoded fileds

### ISSUE THREAD

**Issue by harundogdu** [muhammedeminbekoz/Rent-Cars#2]
hardcoded(statik) olarak tanımlanmış alanları env içerisine taşıyalım.

https://github.com/muhammedeminbekoz/Rent-Cars/blob/7e044f3ddb72c4f5eb7e78bdbd65d5d31211f069/src/utils/email.js#L116C1-L117C1

**Comment by muhammedeminbekoz** [comment]
gönderici emaili env dosyasından getirildi
