### ISSUE TITLE
Absolute Path defining

### ISSUE THREAD

**Issue by harundogdu** [muhammedeminbekoz/Rent-Cars#3]
Projede ".../.../" gibi yapılar olmamalı. Bunlar "Absolute path" kavramı ile çözelim. (@controller, @routes vs gibi.)

https://github.com/muhammedeminbekoz/Rent-Cars/blob/7e044f3ddb72c4f5eb7e78bdbd65d5d31211f069/src/controllers/carsController.js#L2

**Comment by muhammedeminbekoz** [comment]
module-aliases paketiyle birlikte rotalar daha düzenli bir hale getirldi.
