### ISSUE TITLE
Refactoring unnecessary log messages and formatting codes.

### ISSUE THREAD

**Issue by harundogdu** [muhammedeminbekoz/Rent-Cars#4]
Gereksiz console.log'ları temizleyelim. ve kodları formatlayarak gönderelim.

https://github.com/muhammedeminbekoz/Rent-Cars/blob/7e044f3ddb72c4f5eb7e78bdbd65d5d31211f069/src/controllers/officeController.js#L12

**Comment by muhammedeminbekoz** [comment]
gereksiz console log lar kaldırıldı
