### ISSUE TITLE
Refactoring urls

### ISSUE THREAD

**Issue by harundogdu** [muhammedeminbekoz/Rent-Cars#5]
URL'lerde bir pattern belirleyelim. Örnek: sendEmail => send-email gibi olsun. Tamamını bu şekilde revize edelim. 

https://github.com/muhammedeminbekoz/Rent-Cars/blob/7e044f3ddb72c4f5eb7e78bdbd65d5d31211f069/src/routers/userRoutes.js#L11

**Comment by muhammedeminbekoz** [comment]
url formatları değiştirildi
